/* eslint-disable @next/next/no-img-element */
"use client";
import "./styles/style.css"
import Breadcrumb  from "../../components/ux/breadcrumb"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header className="header">
        <div style={{ display: "inline-block" }}>
          <h2>MyWebsite</h2>
        </div>
        <div style={{textAlign:"right"}}>
        <button className="button-style"><a href="/" >Home</a></button>
        <button className="button-style"><a href="https://github.com/cr33p1ngp4ck3t" target="_blank">Github</a></button>
        <button className="button-style"><a href="https://www.npmjs.com/~creepingpacket" target="_blank">NPM</a></button>
        </div>
      </header>
      <div className="content">
        <Breadcrumb/>
        {children}
      </div>
      <footer className="footer">
        <div >
          <div ><h2>MyWebsite</h2></div>
        </div>
        <div>
          <div>
            <div>
              <a className="logo" href="https://github.com/cr33p1ngp4ck3t" target="_blank"><img width="26" height="26" src="https://img.icons8.com/ios-filled/50/github.png" alt="github"/></a>
              <a className="logo" href="www.linkedin.com/in/creepingpacket" target="_blank"><img width="26" height="26" src="https://img.icons8.com/ios-filled/50/linkedin.png" alt="linkedin"/></a>
              <a className="logo" href="https://www.npmjs.com/~creepingpacket" target="_blank"><img width="22" height="22" src="https://img.icons8.com/windows/32/npm.png" alt="npm" style={{border:"2px solid #323232", borderRadius:"4px"}}/></a>
            </div>
          </div>
        </div>
      </footer>
      </body>
    </html>
  )
}
